app/auth.py
"""Routes for user authentication."""
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user

from . import login_manager
from .forms import LoginForm, SignupForm
from .models import User, db

# Blueprint Configuration
auth_bp = Blueprint(
    'auth_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    """
    User sign-up page.
    GET requests serve sign-up page.
    POST requests validate form & user creation.
    """
    form = SignupForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(name=form.name.data).first()
        #existing_user=None
        if existing_user is None:
            user = User(
                name=form.name.data,
            )
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()  # Create new user
            login_user(user)  # Log in as newly created user
            return redirect(url_for('main_bp.usr_page',usr=current_user))
        flash('A user already exists with that username.')
    return render_template(
        'signup.jinja2',
        title='Create an Account.',
        form=form,
        template='signup-page',
        body="Sign up for a user account."
    )


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    """
    Log-in page for registered users.
    GET requests serve Log-in page.
    POST requests validate and redirect user to dashboard.
    """
    # Bypass if user is logged in
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.usr_page', usr=current_user))  

    # Validate login attempt
    if form.validate_on_submit():
        user = User.query.filter_by(name=form.name.data).first()  
        if user and user.check_password(password=form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page or url_for('main_bp.usr_page', usr=current_user))
        flash('Invalid username/password combination')
        return redirect(url_for('auth_bp.login'))
    return render_template(
        'login.jinja2',
        form=form,
        title='Log in.',
        template='login-page',
        body="Log in with your User account."
    )


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in upon page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('auth_bp.login'))

app/routes.py
#route declaration
from flask import current_app as app
from flask import request, make_response, session, flash
from datetime import datetime as dt
from .models import db, User, Cookbook, Recipe, Review
from .forms import CookbookForm, RecipeForm, ReviewForm, SearchForm, RecipeFromURLForm
from flask_login import current_user, login_required, logout_user
from .fetch_recipe import scrape_recipe

from flask import(
        Flask,
        url_for,
        render_template,
        redirect,
        Blueprint
)

# Blueprint Configuration
main_bp = Blueprint(
    'main_bp', __name__,
    template_folder='templates',
    static_folder='static'
)

@main_bp.route('/hello_<usr>', methods=['GET'])
@login_required
def usr_page(usr):
    """Logged-in User Page."""
    return render_template(
        'dashboard.jinja2',
        title='logged in page',
        template='dashboard-template',
        current_user=current_user,
        body="You are now logged in!",
        cookbooks=Cookbook.query.filter_by(owner=current_user.name).all()
    )

@main_bp.route('/<other_usr>')
@login_required
def other_usr_page(other_usr):
    return render_template(
        'other_user_dashboard.jinja2',
        title='page for other user',
        other_user=other_usr,
        cookbooks=Cookbook.query.filter_by(owner=other_usr).all()
    )

@main_bp.route('/ckbk_creation', methods=['GET','POST'])
@login_required
def ckbk_creation():
    form=CookbookForm()
    if form.validate_on_submit():
        ckbk= Cookbook(
            title=form.title.data,
            category= form.category.data,
            owner=current_user.name
            )
        db.session.add(ckbk)
        db.session.commit()
        return redirect (url_for('main_bp.usr_page',usr=current_user))
    return render_template('cookbook_f.jinja2', form=form)

@main_bp.route('/recipe_creation',methods=['GET','POST'])
@login_required
def recipe_creation():
    form=RecipeForm()
    cid = session.get('cid', None)
    if form.validate_on_submit():
        recipe= Recipe(
            title=form.title.data,
            authors= form.authors.data,
            url='manual entry',
            cooking_time=form.cooking_time.data,
            amount=form.amount.data,
            ingredients=form.ingredients.data,
            instructions=form.instructions.data,
            description=form.description.data,
            category=form.category.data,
            main_ingredient=form.main_ingredient.data,
            user_owner=current_user.name,
            ckbk_owner=int(cid)
            )
        db.session.add(recipe)
        db.session.commit()
        flash("success")
        return redirect (url_for('main_bp.dis_ckbk', cid=cid))
    else:
        flash(form.errors)
    return render_template('recipe_f.jinja2',form=form)

@main_bp.route('/recipe_creation_from_url',methods=['GET','POST'])
@login_required
def recipe_creation_from_url():
    form=RecipeFromURLForm()
    cid = session.get('cid', None)
    if form.validate_on_submit():
        link=form.url.data
        recipe_info=scrape_recipe(link)
        #print(recipe_info)
        if 'title' in recipe_info:
            recipe=Recipe(
                    title=recipe_info['title'],
                    authors=' ',
                    url=link,
                    cooking_time=recipe_info['time'],
                    amount=recipe_info['yield'],
                    ingredients=', '.join(recipe_info['ingredients']),
                    instructions=recipe_info['instructions'],
                    description=recipe_info['description'],
                    category=recipe_info['category'],
                    main_ingredient='love',
                    user_owner=current_user.name,
                    ckbk_owner=int(cid)
                    )
            db.session.add(recipe)
            db.session.commit()
        if len(recipe_info)==0:
            return render_template('sorry.jinja2')
        return redirect (url_for('main_bp.dis_ckbk', cid=cid))
    return render_template('recipe_url_f.jinja2',form=form)

@main_bp.route('/edit_recipe',methods=['GET','POST'])
@login_required
def edit_recipe():
    rid=session.get('rid',None)
    recipe=Recipe.query.get(int(rid))
    form=RecipeForm(obj=recipe)
    if form.validate_on_submit():
        form.populate_obj(recipe)
        db.session.commit()
        return redirect(url_for('main_bp.dis_recipe', rid=rid))
    return render_template('recipe_f.jinja2',form=form)

@main_bp.route('/leave_review',methods=['GET','POST'])
@login_required
def leave_review():
    form=ReviewForm()
    rid = session.get('rid',None)
    if form.validate_on_submit():
        review= Review(
                recipe_id=int(rid),
                comment=form.comment.data,
                stars=int(form.stars.data)
                )
        db.session.add(review)
        db.session.commit()
        flash("success")
        return redirect(url_for('main_bp.dis_recipe', rid=rid))
    else:
        flash(form.errors)
    return render_template('review_f.jinja2', form=form)

@main_bp.route('/ckbk'+'<cid>', methods=['GET','POST'])
@login_required
def dis_ckbk(cid):
    session['cid']=cid
    return render_template('cookbook_inside.jinja2',
        ckbk_info=Cookbook.query.filter_by(id=cid).all(),
        recipes=Recipe.query.filter_by(ckbk_owner=cid).all()
        )

@main_bp.route('/recipe'+'<rid>', methods=['GET','POST'])
@login_required
def dis_recipe(rid):
    session['rid']=int(rid)
    return render_template('recipe_inside.jinja2',
    recipes=Recipe.query.filter_by(id=rid).all(),
    comments=Review.query.filter_by(recipe_id=rid).all()
    )

@main_bp.route('/search_form', methods=['GET','POST'])
@login_required
def search():
    form=SearchForm()
    if form.validate_on_submit():
        search_param=[]
        title = request.form.get('title', None)
        if title!='':
            search_param.append("title like '%"+title+"%'")
        
        category = request.form.get('category',None)
        if category!='':
            search_param.append("category like '%"+category+"%'")
        
        if form.search_choice.data=='Recipes':
            main_ingredient= request.form.get('main_ingredient',None)
            if main_ingredient!='':
                search_param.append("main_ingredient like '%"+main_ingredient+"%'")
            
            min_rating = request.form.get('min_rating',None)
            conditions=' AND '.join(search_param)
            query="select * from recipe where"+conditions
            recipes=db.session.execute("select * from recipe where "+conditions).all()
            avg_ratings=[]

            if int(min_rating)!=0:
                ratings=db.session.execute("select stars, recipe_id from review, (select * from recipe where "+conditions+") as searched_recipes where searched_recipes.id=recipe_id").all()
                if len(ratings)>0:
                    for recipe in recipes:
                        avg_list=[]
                        for rating in ratings:
                            if int(rating[1])==int(recipe.id):
                                avg_list.append(int(rating[0]))
                        avg=float(sum(avg_list))/float(len(avg_list))
                        avg_ratings.append((recipe.id,avg))
            return render_template('search_page.jinja2', recipes=recipes,avg_ratings=avg_ratings,min_rating=float(min_rating), cookbooks=None)
        else:
            conditions=' AND '.join(search_param)
            query="select * from cookbook where"+conditions
            cookbooks=db.session.execute("select * from cookbook where "+conditions)
            return render_template('search_page.jinja2', cookbooks=cookbooks, recipes=None)
    return render_template('search_f.jinja2', form=form)

@main_bp.route('/site_stats')
@login_required
def stats():
    all_users=db.session.execute("select name from users").all()
    all_stats=[]
    for result in all_users:
        for name in result:
            stats=db.session.execute("select COUNT(distinct recipe.title) as recipe_number, COUNT(distinct cookbook.title) as ckbk_number, user_owner from recipe, cookbook where user_owner='"+name+"' and owner='"+name+"'").all()
            all_stats.append(stats)
    return render_template('stats_page.jinja2', all_stats=all_stats)

@main_bp.route('/search_page')
@login_required
def search_results():
    return render_template('search_page.jinja2')

@main_bp.route("/logout")
@login_required
def logout():
    """User log-out logic."""
    logout_user()
    return redirect(url_for('auth_bp.login'))

@app.route('/')
def home():
    #landing page
    return render_template(
            'home.jinja2'
            )

app/templates/cookbook_f.jinja2
{% block content %}
  <div class="form-wrapper">

    <h1>Create a Cookbook</h1>

    <form method="POST" action="/ckbk_creation">
      {{ form.csrf_token }}

      <fieldset class="title">
        {{ form.title.label }}
        {{ form.title(placeholder='Homecooking') }}
      </fieldset>

      <fieldset class="category">
        {{ form.category.label }}
        {{ form.category }}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

    </form>
  </div>

{% endblock %}

app/templates/cookbook_inside.jinja2
{% block content %}
<head>
<style>
body{background-image:url("{{ url_for('static', filename='/img/veggie_repeat1.jpg') }}");}
.container {
  display: flex;
  text-align: center;
  justify-content: center; /* center the child */
}
h1 {
    display: flex;
    padding:5px;font-size:35px;background-color:green;color:#ffffff;
}

p {
    display: flex;
    padding:5px;font-size:35px;background-color:green;color:#ffffff;
}

a {
    /*display: flex;*/
    padding:5px;font-size:20px;background-color:white;color:hotpink;
}

</style>
</head>

	{% for ckbk in ckbk_info %}
		<div class="container">
		<h1>{{ ckbk.title }}</h1>
		</div>

		{% if current_user.name == ckbk.owner %}
			<div class="container">
			<a href="{{url_for('main_bp.recipe_creation')}}">Add a new recipe</a>
			<a href="{{url_for('main_bp.recipe_creation_from_url')}}">Add a new recipe from url</a>
			</div>
		{% endif %}
	{% endfor %}
	
	<div class="container">
	<h1> Recipes: </h1>
	</div>
        {% for recipe in recipes %}
		<div class="container">
                <a href="{{url_for('main_bp.dis_recipe', rid=recipe.id)}}">{{recipe.title}}</a>
		</div>
        {% endfor %}
	<div class="container">
	<p>------------------------------------------------------------</p>
	</div>
	<div class="container">
	<a href="{{ url_for('main_bp.usr_page', usr=current_user)}}">Return to user page</a>
	</div>
{% endblock %}

app/templates/dashboard.jinja2
{% block content %}

<head>
<style>
body{background-image:url("{{ url_for('static', filename='/img/veggie_repeat1.jpg') }}");}
.container {
  display: flex;
  justify-content: center; /* center the child */
}
h1 {
    display: flex;
    padding:5px;font-size:35px;background-color:green;color:#ffffff;
}

p {
    display: flex;
    padding:5px;font-size:35px;background-color:green;color:#ffffff;
}

a {
    /*display: flex;*/
    padding:5px;font-size:20px;background-color:white;color:hotpink;
}

</style>
</head>

<div class="container">
  <h1>{{ body }}</h1>
</div>
<div class="container">
  <p> Hi {{current_user.name}} </break>!
</div>
<div class="container">
  <a href="{{url_for('main_bp.ckbk_creation')}}">Create a new cookbook</a>
</div>
<div class="container">
  <p>+++</p>
</div>
<div class="container">
  <a href="{{url_for('main_bp.search')}}">Search</a>
</div>
<div class="container">
  <p>+++</p>
</div>
<div class="container">
  <a href="{{ url_for('main_bp.logout') }}">Log out</a>
</div>
<div class="container">
  <p>+++</p>
</div>
<div class="container">
  <a href="{{ url_for('main_bp.stats') }}">Site Statistics</a>
</div>
<div class="container">
  <h1> Your cookbooks: </h1>
</div>
	{% for book in cookbooks %}
		<div class="container">
		<a href="{{url_for('main_bp.dis_ckbk', cid=book.id)}}">{{book.title}}</a>
		</div>
	{% endfor %}

{% endblock %}

app/templates/layout.jinja2
<head>
<style>
body{
        background-image:url("{{ url_for('static', filename='/img/veggies4k.jpg') }}");
        background-attachment: fixed;
    }
</style>
</head>

app/templates/login.jinja2
{% block content %}
  <div class="form-wrapper">

    <h1>Log In</h1>

    <form method="POST" action="/login">
      {{ form.csrf_token }}

      <fieldset class="name">
        {{ form.name.label }}
        {{ form.name(placeholder='John Smith') }}
      </fieldset>

      <fieldset class="password">
        {{ form.password.label }}
        {{ form.password }}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

      <div class="login-signup">
        <span>Don't have an account?</span>
        <a href="{{ url_for('auth_bp.signup') }}">Sign up.</a>
      </div>

    </form>
  </div>

{% endblock %}

app/templates/other_user_dashboard.jinja2
{% block content %}

<head>
<style>
body{background-image:url("{{ url_for('static', filename='/img/veggie_repeat1.jpg') }}");}
.container {
  display: flex;
  justify-content: center; /* center the child */
}
h1 {
    display: flex;
    padding:5px;font-size:35px;background-color:green;color:#ffffff;
}

p {
    display: flex;
    padding:5px;font-size:35px;background-color:green;color:#ffffff;
}

a {
    /*display: flex;*/
    padding:5px;font-size:20px;background-color:white;color:hotpink;
}

</style>
</head>

  <div class="container">
  <h1>This is {{other_user}}'s page!</h1>
  </div>
  <div class="container">
  <a href="{{ url_for('main_bp.stats') }}">Site Statistics</a>
  <a href="{{ url_for('main_bp.usr_page', usr=current_user)}}">Return to your page</a>
  </div>

  <div class="container">
  <h1> Their cookbooks: </h1>
  </div>
        {% for book in cookbooks %}
		<div class="container">
                <a href="{{url_for('main_bp.dis_ckbk', cid=book.id)}}">{{book.title}}</a>
		</div>
        {% endfor %}

{% endblock %}

app/templates/recipe_f.jinja2
{% block content %}
  <div class="form-wrapper">

    <h1>Create a Recipe</h1>
    <p>Please make sure all fields are filled out </p>

    <form method="POST" action="">
      {{ form.csrf_token }}

      <fieldset class="title">
        {{ form.title.label }}
        {{ form.title(placeholder='Chocolate Cake') }}
      </fieldset>

      <fieldset class="authors">
        {{ form.authors.label }}
        {{ form.authors(placeholder='Kate') }}
      </fieldset>

      <fieldset class="cooking_time">
        {{ form.cooking_time.label }}
        {{ form.cooking_time(placeholder='1 hour') }}
      </fieldset>

      <fieldset class="yield">
        {{ form.amount.label }}
        {{ form.amount(placeholder='8 servings') }}
      </fieldset>

      <fieldset class="ingredients">
        {{ form.ingredients.label }}
        {{ form.ingredients(placeholder='2 eggs, 1 cup flour, etc', cols="50",rows="20") }}
      </fieldset>

      <fieldset class="instructions">
        {{ form.instructions.label }}
        {{ form.instructions(placeholder='Whisk together butter and sugar...', cols="50",rows="20") }}
      </fieldset>

     <fieldset class="description">
        {{ form.description.label }}
        {{ form.description(placeholder='My husbands favorite cake') }}
      </fieldset>

      <fieldset class="category">
        {{ form.category.label }}
        {{ form.category(placeholder='Dessert') }}
      </fieldset>

      <fieldset class="main_ingredient">
        {{ form.main_ingredient.label }}
        {{ form.main_ingredient(placeholder='Chocolate') }}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

    </form>
  </div>

{% endblock %}

app/templates/recipe_inside.jinja2
{% block content %}
<head>
<style>
body{background-image:url("{{ url_for('static', filename='/img/veggie_repeat1.jpg') }}");}
.container {
  display: flex;
  align-items: center;
  justify-content: center; /* center the child */
}
h1 {
    padding:5px;font-size:35px;color:#ffffff;
}
h1 span{
   background-color:green;
}

p {
    padding:5px;font-size:20px;color:darkgreen;
}
p span{
   background-color:white;
}

a {
    padding:5px;font-size:20px;background-color:white;color:hotpink;
}

</style>
</head>
        {% for recipe in recipes %}
		<h1><span>Title: {{recipe.title}}</span> </h1>
		<p><span>Authors: {{recipe.authors}}</span> </p>
		<p><span>Description: {{recipe.description}} </span></p>
		<p><span>Category: {{recipe.category}}</span> </p>
		<p><span>Main Ingredient: {{recipe.main_ingredient}}</span> </p>
		<p><span>url: {{recipe.url}}</span> </p>
		<p><span>Cooking Time: {{recipe.cooking_time}}</span> </p>
		<p><span>Yield: {{recipe.amount}}</span> </p>
		<p><span>Ingredients: {{recipe.ingredients}}</span> </p>
		<p><span>Instructions: {{recipe.instructions}}</span> </p>
		{% set ckbk_owner = recipe.ckbk_owner %}
		{% if recipe.user_owner == current_user.name %}
			<a href="{{url_for('main_bp.edit_recipe')}}">Edit Recipe</a>
		{% endif %}
        {% endfor %}

	<a href="{{url_for('main_bp.leave_review')}}">Leave a Comment</a>

		<h1><span> Reviews</span> </h1>
	{% for comment in comments %}
		<p> <span>comment: {{comment.comment}}
		    stars: {{comment.stars}}</span> </p>
		<p><span> ----------------------------------------------------------------------------------</span></p>
	{% endfor %}
	<a href="{{url_for('main_bp.usr_page',usr=current_user)}}">Return to User Page</a>
	<a href="{{url_for('main_bp.dis_ckbk',cid=ckbk_owner)}}"Return to Cookbook</a>
{% endblock %}

app/templates/recipe_url_f.jinja2
{% block content %}
  <div class="form-wrapper">

    <h1>Create a Recipe from a URL</h1>
    <p> This will attempt to create a recipe from a url. This function may not work on all urls and the information will likely need to be edited. </p>

    <form method="POST" action="">
      {{ form.csrf_token }}

      <fieldset class="url">
        {{ form.url.label }}
        {{ form.url(placeholder='www.cookbook_recipe_link.com') }}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

    </form>
  </div>

{% endblock %}

app/templates/review_f.jinja2
{% block content %}
  <div class="form-wrapper">

    <h1>Leave a Review</h1>

    <form method="POST" action="/leave_review">
      {{ form.csrf_token }}

      <fieldset class="comment">
        {{ form.comment.label }}
        {{ form.comment }}
      </fieldset>

      <fieldset class="stars">
        {{ form.stars.label }}
        {{ form.stars }}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

    </form>
  </div>

{% endblock %}

{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
{% block body %}{% endblock %}

app/templates/search_f.jinja2
{% block content %}
  <div class="form-wrapper">

    <h1>Search</h1>

    <p>Please choose to search either cookbooks or recipes. If only searching cookbooks, don't fill out
       the fields 'Main Ingredient' or 'Minimum Rating.'</p>

    <form method="POST" action="/search_form">
      {{ form.csrf_token }}

      <fieldset class="search_choice">
        {{ form.search_choice.label }}
        {{ form.search_choice }}
      </fieldset>

      <fieldset class="title">
        {{ form.title.label }}
        {{ form.title }}
      </fieldset>

      <fieldset class="category">
        {{ form.category.label }}
        {{ form.category }}
      </fieldset>

      <fieldset class="main_ingredient">
        {{ form.main_ingredient.label }}
        {{ form.main_ingredient }}
      </fieldset>

      <fieldset class="min_rating">
        {{ form.min_rating.label }}
        {{ form.min_rating }}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

    </form>
  </div>

{% endblock %}

{% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}
{% block body %}{% endblock %}

app/templates/search_page.jinja2
{% block content %}
<head>
<style>
body{background-image:url("{{ url_for('static', filename='/img/veggie_repeat1.jpg') }}");}
.container {
  display: flex;
  justify-content: center; /* center the child */
}
h1 {
    display: flex;
    padding:5px;font-size:35px;background-color:green;color:#ffffff;
}

p {
    display: flex;
    padding:5px;font-size:20px;background-color:white;color:darkgreen;
}

a {
    display: flex;
    padding:5px;font-size:20px;background-color:white;color:hotpink;
}

</style>
</head>

	<div class="container">
        <h1>Search Results</h1>
	</div>

	{% if recipes is not none %}
		{% if min_rating != 0.0 %}
			{% if avg_ratings|length == 0 %}
				<div class="container">
				<p> No results were found </p>
				</div>
			{% endif %}
        		{% for recipe in recipes %}
				{% for rating in avg_ratings %}
					{% if rating[0] == recipe.id and rating[1] >= min_rating %}
						<div class="container">
						<a href="{{url_for('main_bp.dis_recipe', rid=recipe.id)}}"><b>{{recipe.title}}</b></a>
						</div>
						<div class="container">
						<p>{{recipe.description}},</p>
						<p>Average Rating: {{rating[1]}} </p>
						</div>
						<div class="container">
						<p><b>------------------------------------------------------------------------------------------------------</b></p>
						</div>
					{% endif %}
				{% endfor %}
        		{% endfor %}
		{% else %}
			{% for recipe in recipes %}
				<div class="container">
				<a href="{{url_for('main_bp.dis_recipe', rid=recipe.id)}}"><b>{{recipe.title}}</b></a> 
				</div>
				<div class="container">
				<p>{{recipe.description}}</p>
				</div>
				<div class="container">
                                <p><b>------------------------------------------------------------------------------------------------------</b></p>
				</div>
                        {% endfor %}
		{% endif %}
	{% endif %}

	{% if cookbooks is not none %}
		{% for ckbk in cookbooks %}
			<div class="container">
			<a href="{{url_for('main_bp.dis_ckbk', cid=ckbk.id)}}">{{ckbk.title}}</a>
			</div>
		{% endfor %}
	{% endif %}

	{% if cookbooks is none and recipes is none %}
		<div class="container">
		<p> No results were found </p>
		</div>
	{% endif %}
	
	<div class="container">
	<a href="{{url_for('main_bp.usr_page', usr =current_user )}}">Back to User Page</a>
	<div class="container">
{% endblock %}

app/templates/signup.jinja2
{% block content %}
  <div class="form-wrapper">

    <h1>Sign Up</h1>

    <form method="POST" action="/signup">
      {{ form.csrf_token }}

      <fieldset class="name">
        {{ form.name.label }}
        {{ form.name(placeholder='John Smith') }}
      </fieldset>

      <fieldset class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.password.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="confirm">
        {{ form.confirm.label }}
        {{ form.confirm }}
        {% if form.confirm.errors %}
          <ul class="errors">
            {% for error in form.confirm.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

    </form>

    <div class="login-signup">
      <div>
        <span>Already have an account?</span>
        <a href="{{ url_for('auth_bp.login') }}">Log in.</a>
      </div>
    </div>
  </div>

{% endblock %}

app/templates/stats_page.jinja2
{% block content %}
<head>
<style>
body{background-image:url("{{ url_for('static', filename='/img/veggie_repeat1.jpg') }}");}
.container {
  display: flex;
  justify-content: center; /* center the child */
}
h1 {
    display: flex;
    padding:5px;font-size:35px;background-color:green;color:#ffffff;
}

p {
    display: flex;
    padding:5px;font-size:20px;background-color:white;color:darkgreen;
}

a {
    /*display: flex;*/
    padding:5px;font-size:20px;background-color:#ffffe6;color:hotpink;
}

</style>
</head>
	<div class="container">
	<h1> User Statistics </h1>
	</div>
	{% for stats in all_stats %}
		{% for stat in stats %}
			<div class="container">
			<a href="{{url_for('main_bp.other_usr_page', other_usr=stat.user_owner)}}">{{stat.user_owner}}</a>
			</div>
			<div class="container"> 
			<p>Number of Cookbooks:{{stat.ckbk_number}}</p>
			</div>
			<div class="container">
			<p>Number of Recipes:{{stat.recipe_number}}</p>
			</div>
			<div class="container">
			<p><b>-----------------------------------------------------------------------------------</b></p>
			</div>
		{% endfor %}
	{% endfor %}
{% endblock %}